name: laravel
description: Laravel 10 application with MySQL and Redis
base_overlay: php
tech_stack:
  - PHP 8.1
  - Laravel 10
  - MySQL 8
  - Redis
  - Composer
features:
  - Hot reload
  - Database migrations
  - Authentication
  - Queue processing
  - API routes
ports:
  - "8000:8000"
  - "8080:8080"
services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - "./:/var/www/html"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - dev
    networks:
      - "dev-network"
  db:
    image: mysql:8.0
    environment:
      - "MYSQL_DATABASE={{PROJECT_NAME}}"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=rootpassword"
    volumes:
      - "mysql_data:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - "dev-network"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - "dev-network"
environment:
  DB_CONNECTION: "mysql"
  DB_HOST: "db"
  DB_PORT: "3306"
  DB_DATABASE: "{{PROJECT_NAME}}"
  DB_USERNAME: "user"
  DB_PASSWORD: "password"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
